### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [yesodweb/shakespeare#261]
```
shakespeare                    > /tmp/stack-b71b5994b92c4583/shakespeare-2.0.25/Text/Julius.hs:120:23: error:
shakespeare                    >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
shakespeare                    >                      with: H.HashMap T.Text Value
shakespeare                    >       Expected: H.HashMap T.Text Value
shakespeare                    >         Actual: aeson-2.0.2.0:Data.Aeson.Types.Internal.Object
shakespeare                    >     • In the first argument of ‘H.toList’, namely ‘m’
shakespeare                    >       In the expression: H.toList m
shakespeare                    >       In the expression:
shakespeare                    >         case H.toList m of
shakespeare                    >           (x : xs) -> singleton '{' <> one x <> foldr f (singleton '}') xs
shakespeare                    >           _ -> "{}"
shakespeare                    >     |          
shakespeare                    > 120 |         case H.toList m of
shakespeare                    >     |                       ^
```

**Comment by ocharles** [comment]
I think this was fixed in https://github.com/yesodweb/shakespeare/commit/1c26762941ee5dc9d06177c677c5f48d5d30d8bd?

**Comment by snoyberg** [comment]
Good catch thanks!

**Comment by simonmichael** [comment]
Just a reminder: marked fixed, but not released yet.

**Comment by snoyberg** [comment]
Sorry about that! Somehow I screwed up the upload before. I've released a new version.

**Comment by juhp** [comment]
Thanks!
