### ISSUE TITLE
shakespeare-1.0.4 does not build with GHC 7.0.4 due to missing <> import

### ISSUE THREAD

**Issue by simonmichael** [yesodweb/shakespeare#101]
```
Building shakespeare-1.0.4...
[1 of 2] Compiling Text.Shakespeare.Base ( Text/Shakespeare/Base.hs, dist/build/Text/Shakespeare/Base.o )
[2 of 2] Compiling Text.Shakespeare ( Text/Shakespeare.hs, dist/build/Text/Shakespeare.o )

Text/Shakespeare.hs:234:61: Not in scope: `<>'
...
```

Maybe an import Data.Monoid ((<>)) will help ?
